// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using SuitAlterations.Infrastructure.Database;

namespace SuitAlterations.Infrastructure.Migrations
{
	[DbContext(typeof(ApplicationDbContext))]
	partial class ApplicationDbContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "3.1.1")
				.HasAnnotation("Relational:MaxIdentifierLength", 128)
				.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

			modelBuilder.Entity("SuitAlterations.Domain.Customers.Customer", b =>
			{
				b.Property<Guid>("Id")
					.HasColumnType("uniqueidentifier");

				b.Property<string>("FirstName")
					.HasColumnType("nvarchar(50)")
					.HasMaxLength(50);

				b.Property<string>("LastName")
					.HasColumnType("nvarchar(50)")
					.HasMaxLength(50);

				b.HasKey("Id");

				b.ToTable("Customers", "dbo");
			});

			modelBuilder.Entity("SuitAlterations.Domain.SuitAlterations.SuitAlteration", b =>
			{
				b.Property<Guid>("Id")
					.HasColumnType("uniqueidentifier");

				b.Property<Guid>("CustomerId")
					.HasColumnType("uniqueidentifier");

				b.Property<int>("LeftSleeveLength")
					.HasColumnType("int");

				b.Property<int>("LeftTrouserLength")
					.HasColumnType("int");

				b.Property<int>("RightSleeveLength")
					.HasColumnType("int");

				b.Property<int>("RightTrouserLength")
					.HasColumnType("int");

				b.Property<byte>("Status")
					.HasColumnType("tinyint");

				b.HasKey("Id");

				b.HasIndex("CustomerId");

				b.ToTable("SuitAlterations", "dbo");
			});

			modelBuilder.Entity("SuitAlterations.Domain.SuitAlterations.SuitAlteration", b =>
			{
				b.HasOne("SuitAlterations.Domain.Customers.Customer", null)
					.WithMany("SuitAlterations")
					.HasForeignKey("CustomerId")
					.OnDelete(DeleteBehavior.Cascade)
					.IsRequired();
			});
#pragma warning restore 612, 618
		}
	}
}